version: '3.8'

services:
  python_service:
    build:
      context: .
      dockerfile: DockerFile.network
      args:
        BASE_IMAGE: python:3.9
        APP_VERSION: 1.0
    image: suryahub01/network_topology:1.0
    container_name: network_topology
    environment:
      - DEBUG=true

