# Use official Python slim image
FROM python:3.9-slim

# Metadata
LABEL maintainer="suryatheking5784@gmail.com"
LABEL version="1.0"

# Set environment variable to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        sshpass \
        git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Ansible using pip (no need to install python3-pip separately, it's already available in python image)
RUN pip install --no-cache-dir ansible

# Declare a volume for sharing playbooks or scripts
VOLUME ["/var/lib/ansible_data"]

# Set working directory
WORKDIR /app

# Copy all files from current dir into the container's /app
COPY . /app

# Default command: open a bash shell
CMD ["/bin/bash"]
